### ISSUE TITLE
Checklist for updating lessons according to esmvaltool/esmvalcore 2.8

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#278]
**lesson Configuration**: 
- [x] Download options in` config_user.yml` are changed, More details are given in [#1935](https://github.com/ESMValGroup/ESMValCore/pull/1935) and the [documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=search_esgf#user-configuration-file). 
- [x] Add instructions on how to download from esgf, see #275 

**lesson Running your first recipe**: 
- [x] [recipe_python.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/examples/recipe_python.yml) is changed, updates needed for dataset, preprocessor and location.
- [x] add instructions about `location` and `timerange`.

**lesson Installation**:
- [x]  command using mamba does not need python version

**lesson Debugging**
- [ ] [recipe_python.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/examples/recipe_python.yml) is changed.

**lesson Writing your own diagnostic script**
- [x] example [diagnostic.py](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/diag_scripts/examples/diagnostic.py) is changed.

**Comment by rswamina** [comment]
@SarahAlidoost - I am creating a new issue for the changes to be made under basic topics in preparation for the tutorial this week. Please see [280](https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/280).
