### ISSUE TITLE
Checklist for updating basic tutorial lessons for v2.8

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#280]
This issue addresses `basic lesson` changes including `setup` for ESMValTool and ESMValCore 2.8. It references the following checklist from [278](https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/278).

**lesson Configuration**: 
- [x] Download options in` config_user.yml` are changed, More details are given in [#1935](https://github.com/ESMValGroup/ESMValCore/pull/1935) and the [documentation](https://docs.esmvaltool.org/projects/ESMValCore/en/latest/quickstart/configure.html?highlight=search_esgf#user-configuration-file). 
- [x] Add instructions on how to download from esgf, see #275 

**lesson Running your first recipe**: 
- [x] [recipe_python.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/examples/recipe_python.yml) is changed, updates needed for dataset, preprocessor and location.
- [x] add instructions about `location` and `timerange`.

**lesson Installation**:
- [x]  command using mamba does not need python version
