### ISSUE TITLE
Building an online ESMValTool tutorial

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValTool_Tutorial#3]
This Issue summarises and build on the the Discussion at the ESMValTool core developers workshop on 11/03/2020. 

**To summarise the discussion:**

- We're not confident that EGU 2020 will go ahead. So instead of preparing for a meeting which may not happen, we will produce a tutorial that can be taught online, in person, as a webinar, or could even be done without the help of a an ESMValTool expert.

- There is already a skeleton Tutorial in the e-science academy and we can use this as a basis for the ESMValTool online tutorial:
  - https://escience-academy.github.io/lesson-esmvaltool/
  - https://github.com/escience-academy/lesson-esmvaltool
  - We need to move this tutorial to Github and create a new repository in ESMValGroup. We didn't agree on a repository name, but presumably ESMValTutorial or ESMValTool_Turorial or simply Tutorial would be fine.

- Once this repository has been set up, Lee, V and Ranjini (if she's free) will populate it with our tutorial resources.

- The final tutorial webpage can be hosted on github pages, but we want to make sure we don't add another address to the long list of ESMValTool website. (ESMvaltool project page, ESMValTool github page, readthedocs, the GMD paper, etc...)

- A potential issue with these kind of tutorials is that students may get used to the virtual box or jupyter environment and not be able to move to a "real" environment. We must include instructions on how to transition to a typical ESMValTool conda environment at the end of the beginner tutorial.

Personally, I think that this method, if successful, would be a significant improvement of the current ad hoc tutorial methods. Also, this could hopefully drive many more first time users than we could ever attract at 8:30am on Monday morning of the EGU during a viral outbreak!

This translate to the following actions:

- [x] Create new tutorial repository.
- [ ] Populate the new tutorial @ledm @valeriupredoi @rswamina 
- [x] Add tools for developpers to make local builds of the tutorial #10 #15
- [x] Add environment.yml #10 #15
- [ ] Decide on VM, Jasmin, Jupyter, etc #16
- [x] Add a “pull request-template” #18 #19 
- [x] Add an “issue-template” #20 #21 
- [ ] Update the CONTRIBUTING.md
- [ ] Update/check the license
- [x] Decide on an "esmvaltool lesson-template" #17 
- [ ] Publish the tutorial (e.g. in zenodo)
- [ ]  ... 

Please add additional actions.

**Comment by Peter9192** [comment]
name: ESMValTraining ?

**Comment by ledm** [comment]
Instuctions on how to build a software carpentry lesson are here: 

https://carpentries.github.io/lesson-example/

**Comment by SarahAlidoost** [comment]
I added more items to the action list. @ledm What do you think? To address each item, a sperate issue can be made. I noticed that you are already working on some of them.
Also, would you please have a look at my comments on two items below. Thanks. 

> Add a section on how to transition from the tutorial to the real thing.

This item is not clear to me. Please make it specific.

> Test the tutorial

Can we break this item to sub-items based on lesson life-cycle, please see 
https://carpentries.github.io/curriculum-development/the-lesson-life-cycle.html

**Comment by ledm** [comment]
Thanks, we need to do all sorts of stuff to get this off the ground.
