### ISSUE TITLE
Checklist for compatibility with ESMValTool v2.10.0

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#309]
- [ ] Update lessons on basic topics.
- [ ] Update lessons on advanced topics.
- [ ] Ensure that the current version compatibility is displayed in lessons.
- [ ] Fix pending Issues [298](https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/299)and [299](https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/299)
